baseURL = "https://vshawn.github.io/PRemoteM-Test/"
canonifyurls = true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ezhil"
builddrafts = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/"